version: '3'

services:
  mywebapiapp:
    image: mywebapiapp
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./publish:/app
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - database
  database:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1
    ports:
      - 14330:1433