version: '3'

services:
  test:
    image: test
    build:
      context: ./tests/integration
      dockerfile: Dockerfile
    depends_on:
      - webapi
  webapi:
    image: webapi
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1